.dashVega_js_metadata <- function() {
deps_metadata <- list(`dash_vega` = structure(list(name = "dash_vega",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-Vega.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVega",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vega` = structure(list(name = "dash_vega",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-Vega.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVega",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vega` = structure(list(name = "dash_vega",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_vega.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVega",
all_files = FALSE), class = "html_dependency"),
`dash_vega` = structure(list(name = "dash_vega",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_vega.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVega",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
